trigger:
  - develop

jobs:
  - job: BuildiOS
    pool:
      vmImage: 'macOs-latest'
      demands: xcode
    steps:
      - bash: |
          git clone https://github.com/flutter/flutter.git
          export PATH=`pwd`/flutter/bin:$PATH
          flutter channel stable
          flutter doctor
          echo "Installed flutter to `pwd`/flutter"
        displayName: 'Configure flutter SDK'

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: '$(p12FileName)'
          certPwd: '$(p12Password)'
          keychain: 'temp'
          deleteCert: true
        displayName: 'Install destribution certificate'

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provisioningProfileLocation: 'secureFiles'
          provProfileSecureFile: '$(provisioningProfile)'
          removeProfile: true
        displayName: 'Install provisioning profile'

      - bash: |
          export PATH=`pwd`/flutter/bin:$PATH
          cd dsm_manager_app
          flutter build ios --release
        displayName: 'Build iOS'

      - task: CopyFiles@2
        displayName: 'Copy artifacts'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: |
            **/build/**/*.ipa
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'

      - task: AppCenterDistribute@3
        inputs:
          serverEndpoint: '$(AppCenterConnection)'
          appSlug: '$(appSlugIos)'
          appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
          releaseNotesOption: 'input'
          releaseNotesInput: 'New package release ready.'
          destinationType: 'groups'

  - job: BuildAndroid
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          git clone https://github.com/flutter/flutter.git
          export PATH=`pwd`/flutter/bin:$PATH
          flutter channel stable
          flutter doctor
          echo "Installed flutter to `pwd`/flutter"
        displayName: 'Configure flutter SDK'
      - bash: |
          export PATH=`pwd`/flutter/bin:$PATH
          cd dsm_manager_app
          flutter build apk --release
        displayName: 'Build Android'

      - task: AndroidSigning@3
        inputs:
          apkFiles: '**/build/app/outputs/apk/release/*.apk'
          apksign: true
          apksignerKeystoreFile: key.jks
          apksignerKeystorePassword: $(keypassword)
          apksignerKeystoreAlias: $(key)
          apksignerKeyPassword: $(keypassword)
        displayName: 'Signing and aligning APK file(s)'

      - task: CopyFiles@2
        displayName: 'Copy artifacts'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: |
            **/build/app/outputs/apk/release/*.apk
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
      - task: AppCenterDistribute@3
        inputs:
          serverEndpoint: '$(AppCenterConnection)'
          appSlug: '$(appSlugAndroid)'
          appFile: '$(build.artifactstagingdirectory)/**/*.apk'
          releaseNotesOption: 'input'
          releaseNotesInput: 'New package release ready.'
          destinationType: 'groups'
